BizApp/Areas/Admin/Models/FeatureViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BizApp.Areas.Admin.Models
{
	public class FeatureViewModel
	{
		public int FeatureId { get; set; }
		[Required(ErrorMessage = "نام راوارد کنید")]
		[MaxLength(99, ErrorMessage = "نام بسیار طولانی است")]
		[MinLength(1, ErrorMessage = "نام بسیار کوتاه است")]
		public string Name { get; set; }
		public int FeatureType { get; set;  }
	}
}

BizApp/Areas/Admin/Controllers/FeatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BizApp.Areas.Admin.Models;
using BizApp.Models.Basic;
using BizApp.Utility;
using DataLayer.Infrastructure;
using DomainClass;
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;

namespace BizApp.Areas.Admin.Controllers
{
    [Area("admin")]
    public class FeatureController : Controller
    {
		private IUnitOfWorkRepo _unitofwork;
		private readonly IMapper _mapper;

		public FeatureController(IUnitOfWorkRepo uow, IMapper mapper)
		{
			_unitofwork = uow;
			_mapper = mapper;
		}

		public async Task<IActionResult> Index(string searchString, int? page)
		{
			bool shouldSearch = false;
			try
			{
				if (!string.IsNullOrEmpty(searchString)) shouldSearch = true;

				int pageSize = 5;
				var items = (shouldSearch == false) ?
						await _unitofwork.FeatureRepo.GetAll()
						: await _unitofwork.FeatureRepo.GetAll(searchString);

				var features = items.Select(s => _mapper.Map<Feature, FeatureViewModel>(s))
									.OrderByDescending(o => o.FeatureId);
				PagedList<FeatureViewModel> res = new PagedList<FeatureViewModel>(features.AsQueryable(), page ?? 1, pageSize);
                return View(res);
			}
			catch (Exception)
			{
				return Content(CustomeMessages.Try);
			}
		}

		[HttpPost]
		public async Task<IActionResult> CreateOrUpdate(FeatureViewModel feature)
		{
			ModelState.Remove("FeatureId");
			if (ModelState.IsValid)
			{
				try
				{
					var model = _mapper.Map<Feature>(feature);
					await _unitofwork.FeatureRepo.AddOrUpdate(model);
					await _unitofwork.SaveAsync();
				}
				catch //(Exception ex)
				{
					return Json(new { success = false, responseText = CustomeMessages.Fail });

				}
				return Json(new { success = true, responseText = CustomeMessages.Succcess });

			}

			return Json(new { success = false, responseText = CustomeMessages.Empty });

		}

		[HttpPost]
		public async Task<IActionResult> Remove(int featureId)
		{
			var entity = await _unitofwork.FeatureRepo.GetById(featureId);
			try
			{
				_unitofwork.FeatureRepo.Remove(entity);
				await _unitofwork.SaveAsync();

				return Json(new { success = true, responseText = CustomeMessages.Succcess });

			}
			catch (Exception)
			{
				return Json(new { success = false, responseText = CustomeMessages.Fail });
			}
		}

		public async Task<IActionResult> GetById(int ItemId)
		{
			if (ItemId == 0)
			{
				return NotFound();
			}

			var feature = await _unitofwork.FeatureRepo.GetById(ItemId);
			if (feature == null)
			{
				return NotFound();
			}


			var model = _mapper.Map<FeatureViewModel>(feature);
			List<EditViewModels> FeatureTypeItem = new List<EditViewModels>();

			var edit = new List<EditViewModels>
			{
				new EditViewModels { key = "Name", value = model.Name },
				new EditViewModels { key = "FeatureId", value = model.FeatureId.ToString() },
			
			};
			FeatureTypeItem.Add(new EditViewModels() { key = model.FeatureType.ToString(), value = "" });

			return Json(new { success = true, listItem = edit.ToList(), majoritem = ItemId , featuretype = FeatureTypeItem });
		}
	}
}

BizApp/Areas/Admin/Views/Feature/Index.cshtml
@model PagedList.Core.IPagedList<BizApp.Areas.Admin.Models.FeatureViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="header-secondary row gray-bg">
    <div class="col-lg-12">
        <div class="page-heading clearfix">
            <h1 class="page-title pull-left"> ویژگی ها</h1><a class="btn btn-primary btn-sm btn-add openmodal" href="#" data-toggle="modal" data-target="#myModal">ویژگی جدید</a>
        </div>
        <!-- Breadcrumb -->
        <ol class="breadcrumb breadcrumb-2">
            <li><a href="#"><i class="fa fa-home"></i> خانه</a></li>
            <li class="active"><strong>ویژگی ها</strong></li>
        </ol>

    </div>
</div>

<div class="row filter-wrapper visible-box" id="filter-box">
    <div class="col-lg-12">
        <div class="filter-header">
            <h3 class="title">جستجو</h3>
        </div>
        @using (Html.BeginForm("Index", "Feature", FormMethod.Get))
        {
            <div class="form-inline">
                <div class="form-group">
                    <input name="searchString" placeholder="نام ویژگی را وارد کنید" class="form-control">
                </div>
                <div class="form-group">
                    <button class="btn btn-default">جستجو</button>
                </div>
                <div class="form-group">
                    <a href="/admin/Feature/" class="btn btn-default">مشاهده همه</a>
                </div>
            </div>
        }
    </div>
</div>





<div class="main-content">
    <div class="row">
        <div class="col-lg-12 animatedParent animateOnce z-index-50">
            <div class="panel panel-default animated fadeInUp">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title">ویژگی ها</h3>
                    <ul class="panel-tool-options">
                        <li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>
                    </ul>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-border table-hover dataTables-example">
                            <thead>
                                <tr>
                                    <th>
                                        ردیف
                                    </th>
                                    <th>
                                        نام
                                    </th>
                                    <th>
                                        نوع ویژگی
                                    </th>
                                    <th>
                                        عملیات
                                    </th>
                                </tr>
                            </thead>
                            @{ int rowNo = 0; }
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @(++rowNo)
                                    </td>
                                    <td>
                                        @item.Name
                                    </td>

                                    @{
                                        if (item.FeatureType == 1)
                                        {
                                            <td>دارای مقدار</td>
                                        }
                                        else
                                        {
                                            <td>چنین ویژگی دارد یا خیر</td>

                                        }
                                    }





                                    <td>
                                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#QuestionModal" onclick="AssignButtonClicked(this)" data-assigned-id="@item.FeatureId">حذف</button> |
                                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#EditModal" id="@item.FeatureId"> ویرایش</button>
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                        </div>
                        <div class="col-sm-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                <ul class="pagination">
                                    <li>
                                        <pager list="@Model" asp-controller="Feature" asp-action="Index" asp-area="admin" />
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="myModal" role="dialog" style="height:auto;overflow-y:visible">
    <div class="modal-dialog modal-sm" style="width:400px">
        <div class="modal-content">
            <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">ثبت جدید</h4>
            </div>
            <div class="modal-body" style="height:auto">
                <form id="register">
                    <input id="FeatureId" name="FeatureId" hidden />
                    <div class="form-group" style="margin-right:5px">
                        <label for="Name"> نام :</label>
                        <input display="نام" id="Name" name="Name" placeholder="نام ویژگی را وارد کنید" class="form-control" style="width:70%" required>
                    </div>
                    <div class="form-group" style="margin-right:5px">
                        <label for="exampleInputEmail1"> نوع ویژگی :</label>
                        <select class="form-control" style="width:70%" id="FeatureType" name="FeatureType">
                            <option value="0">چنین ویژگی دارد یا خیر</option>
                            <option value="1">دارای مقدار</option>

                        </select>

                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">انصراف</button>
                <button type="button" class="btn btn-success" onclick="Save();">ثبت</button>
            </div>
        </div>
    </div>
</div>
<div id="Error"></div>
<div id="Success"></div>
<div id="Question"></div>
<script>
    window.onload = Load;
    function Load() {
        CreateAllModals();
        $(".openmodal").click(function () {
            clear('register', ["input"]);
        });
        $(".btn-warning").click(function () {
            EditAjax("/admin/feature/GetById", this.id);
            var bodyStyle = document.body.style;
            bodyStyle.removeProperty('padding-right');
        });
        $('.pagination > li:first-child > a, .pagination > li:first-child > span').html('قبلی')
        $('.pagination>li:last-child>a, .pagination>li:last-child>span').html('بعدی')

    }
    function Save() {
        if (checkvalidity('register') === 0) {
            return;
        }
        else {
            $("#myModal").modal('toggle');
            var Parameters = [{ id: "Name", htmlname: "Name", special: "" }, { id: "FeatureType", htmlname: "FeatureType", special: "combo" }, { id: "FeatureId", htmlname: "FeatureId", special: "" }];
            PostAjax('/admin/feature/CreateOrUpdate', Parameters, "/admin/feature/Index");
        }
    }
    function AssignButtonClicked(elem) {
        $('#FeatureId').val($(elem).data('assigned-id'));
    }
    function Remove() {
        var Parameters = [{ id: "FeatureId", htmlname: "FeatureId", special: "" }];
        PostAjax('/admin/Feature/Remove', Parameters, "/admin/Feature/Index");
    }


</script>