BizApp/Areas/Admin/Models/ProvinceViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BizApp.Areas.Admin.Models
{
	public class ProvinceViewModel
	{
		public int ProvinceId { get; set; }
		[Required(ErrorMessage = "نام راوارد کنید")]
		[MaxLength(50, ErrorMessage = "نام بسیار طولانی است")]
		[MinLength(1, ErrorMessage = "نام بسیار کوتاه است")]
		[DisplayName("نام")]
		public string Name { get; set; }
	}
}

BizApp/Areas/Admin/Controllers/ProvinceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BizApp.Areas.Admin.Models;
using BizApp.Models.Basic;
using BizApp.Utility;
using DataLayer.Infrastructure;
using DomainClass;
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;

namespace BizApp.Areas.Admin.Controllers
{
	[Area("admin")]
	//[Route("admin/province")]
	public class ProvinceController : Controller
	{
		private IUnitOfWorkRepo _unitofwork;
		private readonly IMapper _mapper;

		public ProvinceController(IUnitOfWorkRepo uow, IMapper mapper)
		{
			_unitofwork = uow;
			_mapper = mapper;
		}

		public async Task<IActionResult> Index(string searchString, int? page)
		{
			bool shouldSearch = false;
			try
			{
				if (!string.IsNullOrEmpty(searchString)) shouldSearch = true;

				int pageSize = 5;
				var items = (shouldSearch == false) ?
						await _unitofwork.ProvinceRepo.GetAll()
						: await _unitofwork.ProvinceRepo.GetAll(searchString);

				var provinces = items.Select(s => new ProvinceViewModel { ProvinceId = s.Id, Name = s.Name })
									.OrderByDescending(o => o.ProvinceId);
				PagedList<ProvinceViewModel> res = new PagedList<ProvinceViewModel>(provinces.AsQueryable(), page ?? 1, pageSize);
                return View(res);
			}
			catch (Exception)
			{
				return Content(CustomeMessages.Try);
			}
		}

		[HttpPost]
		public async Task<IActionResult> CreateOrUpdate(ProvinceViewModel province)
		{
			ModelState.Remove("ProvinceId");
			if (ModelState.IsValid)
			{
				try
				{
					var model = _mapper.Map<Province>(province);
					await _unitofwork.ProvinceRepo.AddOrUpdate(model);
					await _unitofwork.SaveAsync();
				}
				catch //(Exception ex)
				{
					return Json(new { success = false, responseText = CustomeMessages.Fail });

				}
				return Json(new { success = true, responseText = CustomeMessages.Succcess });

			}

			return Json(new { success = false, responseText = CustomeMessages.Empty });

		}

		[HttpPost]
		public async Task<IActionResult> Remove(int provinceId) 
		{
			var model = await _unitofwork.ProvinceRepo.GetById(provinceId);
			try
			{
				_unitofwork.ProvinceRepo.Remove(model);
				await _unitofwork.SaveAsync();

				return Json(new { success = true, responseText = CustomeMessages.Succcess });

			}
			catch (Exception)
			{
				return Json(new { success = false, responseText = CustomeMessages.Fail });
			}
		}

		public async Task<IActionResult> GetById(int ItemId)
		{
			if (ItemId == 0)
			{
				return NotFound();
			}

			var province = await _unitofwork.ProvinceRepo.GetById(ItemId);
			if (province == null)
			{
				return NotFound();
			}


			var model = _mapper.Map<ProvinceViewModel>(province);
			var edit = new List<EditViewModels>
			{
				new EditViewModels { key = "Name", value = model.Name },
				new EditViewModels { key = "ProvinceId", value = model.ProvinceId.ToString() }
			};

			return Json(new { success = true, listItem = edit.ToList(), majoritem = ItemId});
		}

	}
}

BizApp/Areas/Admin/Views/Province/Index.cshtml
@model PagedList.Core.IPagedList<BizApp.Areas.Admin.Models.ProvinceViewModel>

@{
    ViewData["Title"] = "Index";
}


<div class="header-secondary row gray-bg">
    <div class="col-lg-12">
        <div class="page-heading clearfix">
            <h1 class="page-title pull-left">استان ها</h1><a class="btn btn-primary btn-sm btn-add openmodal" href="#" data-toggle="modal" data-target="#myModal">استان جدید</a>
        </div>
        <!-- Breadcrumb -->
        <ol class="breadcrumb breadcrumb-2">
            <li><a href="#"><i class="fa fa-home"></i> خانه</a></li>
            <li class="active"><strong>استان ها</strong></li>
        </ol>

    </div>
</div>

<div class="row filter-wrapper visible-box" id="filter-box">
    <div class="col-lg-12">
        <div class="filter-header">
            <h3 class="title">جستجو</h3>
        </div>
        @using (Html.BeginForm("Index", "Province", FormMethod.Get))
        {
            <div class="form-inline">
                <div class="form-group">
                    <input name="searchString" placeholder="نام استان را وارد کنید" class="form-control">
                </div>
                <div class="form-group">
                    <button class="btn btn-default">جستجو</button>
                </div>
                <div class="form-group">
                    <a href="/admin/Province/" class="btn btn-default">مشاهده همه</a>
                </div>
            </div>
        }
    </div>
</div>

<div class="main-content">

    <div class="row">
        <div class="col-lg-12 animatedParent animateOnce z-index-50">
            <div class="panel panel-default animated fadeInUp">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title">استان ها</h3>
                    <ul class="panel-tool-options">
                        <li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>

                    </ul>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-border table-hover dataTables-example">
                            <thead>
                                <tr>
                                    <th>
                                        ردیف
                                    </th>
                                    <th>
                                        نام
                                    </th>
                                    <th>
                                        عملیات
                                    </th>
                                </tr>
                                @{ int rowNo = 0; }
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @(++rowNo)
                                        </td>
                                        <td>
                                            @item.Name
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#QuestionModal" onclick="AssignButtonClicked(this)" data-assigned-id="@item.ProvinceId">حذف</button> |
                                            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#EditModal" id="@item.ProvinceId"> ویرایش</button>
                                        </td>
                                    </tr>
                                }
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                        </div>
                        <div class="col-sm-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                <ul class="pagination">

                                    <li>
                                        <pager list="@Model" asp-controller="Province" asp-action="Index" asp-area="admin" />
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="myModal" role="dialog" style="height:auto;overflow-y:visible">
    <div class="modal-dialog modal-sm" style="width:400px">
        <div class="modal-content">
            <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">ثبت جدید</h4>
            </div>
            <div class="modal-body" style="height:auto">
                <form id="register">
                    <input id="ProvinceId" name="ProvinceId" hidden />
                    <div class="form-group" style="margin-right:5px">
                        <label for="Name"> نام :</label>
                        <input display="نام" id="Name" name="Name" placeholder="نام استان را وارد کنید" class="form-control" style="width:70%" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">انصراف</button>
                <button type="button" class="btn btn-success" onclick="Save();">ثبت</button>
            </div>
        </div>
    </div>
</div>

<div id="Error"></div>
<div id="Success"></div>
<div id="Question"></div>


<script>
    window.onload = Load;
    function Load() {
        CreateAllModals();
        $(".openmodal").click(function () {
            clear('register', ["input"]);
        });
        $(".btn-warning").click(function () {
            EditAjax("/admin/Province/GetById", this.id);
            var bodyStyle = document.body.style;
            bodyStyle.removeProperty('padding-right');
        });
        $('.pagination > li:first-child > a, .pagination > li:first-child > span').html('قبلی')
        $('.pagination>li:last-child>a, .pagination>li:last-child>span').html('بعدی')

    }
    function Save() {
        if (checkvalidity('register') === 0) {
            return;
        }
        else {
            $("#myModal").modal('toggle');
            var Parameters = [{ id: "Name", htmlname: "Name", special: "" }, { id: "ProvinceId", htmlname: "ProvinceId", special: "" }];
            PostAjax('/admin/Province/CreateOrUpdate', Parameters, "/admin/Province/Index");
        }
    }
    function AssignButtonClicked(elem) {
        $('#ProvinceId').val($(elem).data('assigned-id'));
    }
    function Remove() {
        var Parameters = [{ id: "ProvinceId", htmlname: "ProvinceId", special: "" }];
        PostAjax('/admin/Province/Remove', Parameters, "/admin/Province/Index");
    }


</script>